# Generated by Django 6.0.3 on 2026-05-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_status_alter_match_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={},
        ),
    ]
