# Generated by Django 6.0.3 on 2026-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='league_logos/'),
        ),
    ]
