# Generated by Django 6.0.3 on 2026-05-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_league_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueteam',
            name='loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leagueteam',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
