# Generated by Django 6.0.3 on 2026-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_position_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='in_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='starter',
            field=models.BooleanField(default=False),
        ),
    ]
