# Generated by Django 6.0.3 on 2026-05-14 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_status_options'),
        ('players', '0003_player_in_game_player_starter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerstats',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='playerstats',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='player',
            name='in_game',
        ),
        migrations.RemoveField(
            model_name='player',
            name='starter',
        ),
        migrations.AlterField(
            model_name='player',
            name='height_cm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='player_images/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight_kg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlayerMatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_game', models.BooleanField(default=False)),
                ('starter', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_statuses', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_statuses', to='players.player')),
            ],
        ),
    ]
