# Generated by Django 6.0.3 on 2026-05-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_playerstats_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='wingspan_cm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
