# Generated by Django 6.0.3 on 2026-05-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='loss',
        ),
        migrations.RemoveField(
            model_name='team',
            name='win',
        ),
    ]
