# Generated by Django 6.0.3 on 2026-06-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_team_loss_remove_team_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
    ]
