# Generated by Django 6.0.3 on 2026-05-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('matches', '0002_status_alter_match_status'),
        ('players', '0002_position_alter_player_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
